import type { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: '20px',
          }}
        >
          <p>Header part</p>
        </header>

        {children}

        <footer
          style={{
            background: 'magenta',
            padding: '1rem',
          }}
        >
          Footer Part
        </footer>
      </body>
    </html>
  )
}
